config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index new show create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: {
    scope: [ :movie_id, :list_id ]
  }

  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, :through => :bookmarks
  has_one_attached :photo

  validates :name, { uniqueness: true, presence: true }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_and_belongs_to_many :bookmarks

  validates :title, :overview, { uniqueness: true, presence: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    @list.save
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container m-6">

<h1 class="text-center my-4">Add a bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit, class: 'btn btn-primary rounded-pill justify-content-center' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
   <i class="fa-solid fa-video mx-3"> <%= link_to "home", lists_path, class:"text-decoration-none text-dark mx-2"%></i>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
          <%= link_to "Add a list", new_list_path, class: "btn btn-flat mx-4" %>
          </li>
          <!--li class="nav-item"-->

          <!--/li-->
      </ul>
    </div>
  </div>
</div>

  <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,1),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80);">
    <h1>Save your movies</h1>
</div>
<div class="container">
<h2 class="m-5">My lists</h2>


  <div class="card-container">
   <% @lists.each do |list| %>
   <div class="card-category"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
      <%= link_to list.name, list %>
    </div>
  <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container m-6">

<h1 class="text-center my-4">Add a list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-primary rounded-pill text-center' %>
<% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,1),rgba(0,0,0,0.2)), url(<%= cl_image_path @list.photo.key, height: 30 %>);">

<h1 class="text-center my-4"><%= @list.name %></h1>
<%= link_to "Add a bookmart", new_list_bookmark_path(@list), class: 'btn btn-book position-absolute top-50 start-50 translate-middle' %>
</div>
<div class="container">
<br>
<br>


<div class="d-flex justify-content-evenly">
 <% @list.bookmarks.each do |bookmark| %>
 <div class="card-trip">
  <%= image_tag bookmark.movie.poster_url, alt: "movie" %>
    <div class="card-trip-infos">
      <h2 class="mx-2 my-2"><strong><%= bookmark.movie.title %></strong></h2>
     <p class="mx-2"><%= bookmark.comment %></p>
     <br>
  </div>
   <%= link_to "Delete",
        bookmark_path(bookmark), class: 'btn btn-danger text-white btn-sm rounded-pill m-3',
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
      %>
</div>
 <% end %>
</div>


<i class="fa-solid fa-arrow-left"></i><%= link_to "Back to lists", lists_path, class: "text-decoration-none text-dark fw-bold p-2" %>
</div>